<?php

namespace AppBundle\Entity;

/**
 * AnuntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnuntRepository extends \Doctrine\ORM\EntityRepository
{
}
